# Dependencies
markdown:            redcarpet
highlighter:         pygments

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               "Martijn Haex"
tagline:             "Java Consultant"
description:         "Personal Blog of Martijn Haex, Java Consultant."
url:                 http://blog.haexnet.be
baseurl:             /
paginate:            5

# About/contact
author:
  name:              Martijn Haex
  url:               https://twitter.com/martijn_haex
  email:             martijn.haex@c4j.be

# Custom vars
version:             1.0.0